/**
 * Client Form Configuration
 * Defines all form sections and fields programmatically
 * Updated for tab-based layout
 */

export interface FormSectionConfig {
  id: string;
  title: string;
  description: string;
  icon: string;
  fields: string[];
  required: string[];
  priority: "primary" | "secondary";
  availableInCreate: boolean;
  availableInEdit: boolean;
}

/**
 * Field visibility metadata
 * Defines which fields should be excluded from count or are conditionally rendered
 */
const fieldVisibilityRules = {
  // Auto-generated/auto-calculated fields: show but don't count
  autoGenerated: ["subscriptionEndDate"],
  // Edit-only fields: only count in edit mode
  editOnly: ["subscriptionStatus", "paymentStatus"],
} as const;

export const clientFormSections: FormSectionConfig[] = [
  {
    id: "required",
    title: "Required",
    description: "All required fields for client creation",
    icon: "User",
    fields: ["name", "slug", "subscriptionTier", "subscriptionStartDate", "subscriptionEndDate", "subscriptionStatus", "paymentStatus", "businessBrief"],
    required: ["name", "slug", "subscriptionTier", "businessBrief"],
    priority: "primary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "business",
    title: "Business Details",
    description: "Legal name, industry, target audience, content priorities, founding date, organization type",
    icon: "Building2",
    fields: ["legalName", "industryId", "targetAudience", "contentPriorities", "foundingDate", "organizationType"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "contact-seo",
    title: "Contact & SEO",
    description: "Website URL, contact information, SEO metadata, and Google Tag Manager",
    icon: "Mail",
    fields: ["url", "email", "phone", "contactType", "sameAs", "seoTitle", "seoDescription", "description", "canonicalUrl", "metaRobots", "gtmId"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "legal-address",
    title: "Legal & Address",
    description: "Legal information and complete address details",
    icon: "Building2",
    fields: [
      "legalForm",
      "commercialRegistrationNumber",
      "vatID",
      "taxID",
      "licenseNumber",
      "licenseAuthority",
      "addressStreet",
      "addressNeighborhood",
      "addressBuildingNumber",
      "addressAdditionalNumber",
      "addressCity",
      "addressRegion",
      "addressPostalCode",
      "addressCountry",
    ],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
  {
    id: "media-social",
    title: "Media & Social",
    description: "Logo, OG image, Twitter image, and Twitter card settings",
    icon: "Image",
    fields: ["logoMediaId", "ogImageMediaId", "twitterImageMediaId", "twitterCard", "twitterTitle", "twitterDescription", "twitterSite"],
    required: [],
    priority: "secondary",
    availableInCreate: false,
    availableInEdit: true,
  },
  {
    id: "classification-additional",
    title: "Classification & Additional",
    description: "Business codes, employee count, parent organization, alternate name, slogan, keywords, languages",
    icon: "Building2",
    fields: ["businessActivityCode", "isicV4", "numberOfEmployees", "parentOrganizationId", "alternateName", "slogan", "keywords", "knowsLanguage"],
    required: [],
    priority: "secondary",
    availableInCreate: true,
    availableInEdit: true,
  },
] as const;

/**
 * Get all field names from all sections
 */
export function getAllFormFields(): string[] {
  return clientFormSections.flatMap((section) => section.fields);
}

/**
 * Get required fields from all sections
 */
export function getRequiredFields(): string[] {
  return clientFormSections.flatMap((section) => section.required);
}

/**
 * Get sections available in create mode
 */
export function getCreateModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInCreate);
}

/**
 * Get sections available in edit mode
 */
export function getEditModeSections(): FormSectionConfig[] {
  return clientFormSections.filter((section) => section.availableInEdit);
}

/**
 * Get section by ID
 */
export function getSectionById(id: string): FormSectionConfig | undefined {
  return clientFormSections.find((section) => section.id === id);
}

/**
 * Get visible field count for a section
 * Excludes auto-generated fields and conditionally rendered fields based on mode
 * 
 * @param sectionId - The section ID to count fields for
 * @param isEditMode - Whether the form is in edit mode
 * @returns The number of visible fields that should be counted
 */
export function getVisibleFieldCount(sectionId: string, isEditMode: boolean): number {
  const section = getSectionById(sectionId);
  if (!section) return 0;

  return section.fields.filter((field) => {
    // Exclude auto-generated/auto-calculated fields (show but don't count)
    if (fieldVisibilityRules.autoGenerated.includes(field as any)) {
      return false;
    }

    // For edit-only fields, only count in edit mode
    if (fieldVisibilityRules.editOnly.includes(field as any)) {
      return isEditMode;
    }

    // Count all other fields
    return true;
  }).length;
}
