import type { StepConfig } from "./types";

export const STEP_CONFIGS: StepConfig[] = [
  {
    number: 1,
    label: "Basic",
    id: "basic",
    description: "Essential article information: title, slug, client, and author",
    requiredFields: ["title", "slug", "clientId", "authorId"],
    optionalFields: ["categoryId", "excerpt", "status", "featured"],
  },
  {
    number: 2,
    label: "Content",
    id: "content",
    description: "Main article content and formatting options",
    requiredFields: ["content"],
    optionalFields: [
      "contentFormat",
      "wordCount",
      "readingTimeMinutes",
      "contentDepth",
      "articleBodyText",
      "inLanguage",
      "isAccessibleForFree",
    ],
  },
  {
    number: 3,
    label: "Media",
    id: "media",
    description: "Images, featured image, and media gallery",
    requiredFields: [],
    optionalFields: ["featuredImageId", "gallery"],
  },
  {
    number: 4,
    label: "FAQs",
    id: "faqs",
    description: "Frequently asked questions and article tags",
    requiredFields: [],
    optionalFields: ["faqs", "tags"],
  },
  {
    number: 5,
    label: "Settings",
    id: "settings",
    description: "Publishing settings, SEO basics, and technical SEO configuration",
    requiredFields: ["seoTitle", "seoDescription"],
    optionalFields: [
      "scheduledAt",
      "canonicalUrl",
      "metaRobots",
      "sitemapPriority",
      "sitemapChangeFreq",
      "license",
      "mainEntityOfPage",
    ],
  },
  {
    number: 6,
    label: "Related",
    id: "related",
    description: "Related articles and content connections",
    requiredFields: [],
    optionalFields: ["relatedArticles"],
  },
  {
    number: 7,
    label: "Technical SEO",
    id: "seo",
    description: "Preview of search results, social sharing, and structured data",
    requiredFields: [],
    optionalFields: [
      "ogType",
      "ogArticleAuthor",
      "ogArticleModifiedTime",
      "twitterCard",
      "twitterSite",
      "twitterCreator",
      "breadcrumbPath",
    ],
  },
];
